### ISSUE TITLE
updating devices?

### ISSUE THREAD

**Issue by woodie4868** [UniversalDevicesInc/UD-Mobile-iOS#10]
I recently replaced two Togglinc switches (#2466SW) with Switchlincs (#2477S).  I can't find how to update the devices list in the mobile app?  The status for these two devices are now blank and when I try to control them the error message is: "Could not connect to ISY.  Response code 400.  Error null."

**Comment by JavierRefuerzo** [comment]
Hi @woodie4868 ,
Have you tried Settings>Systems>Your Isy>Save, then synchronize?

**Comment by woodie4868** [comment]
Javi,

Ah, that worked.  I didn’t realize the synchronize window would pop up after hitting save, especially when I hadn’t made any changes to the remote connection settings.    It might be useful to add a note to that effect on the setting/system page.

Thanks,

John

**Comment by JavierRefuerzo** [comment]
Hi John,

Sync will be moved to the home screen like on Android at some point in the future.  I currently have another project which requires all of my attention, but should start updates soon.
