### ISSUE TITLE
Updates to Programs (need additional information)

### ISSUE THREAD

**Issue by kj4qyf** [UniversalDevicesInc/UD-Mobile-iOS#11]
I noticed that the App  does not show the updates that I made to my ISY programs.

**Comment by JavierRefuerzo** [comment]
Hi Asbirl, 

I please elaborate.  If this is related to issue #8 it should be fixed in the next update

**Comment by JavierRefuerzo** [comment]
Ok, they are not related.  A resync is required any time nodes/programs/ect are changed.  To do this go to your ISY in the app, save then sync.  This will be moved to the home screen in the future.  Please let me know if this fixes the issue.

**Comment by kj4qyf** [comment]
After save the synch gets stuck here

**Comment by JavierRefuerzo** [comment]
Ok, I'll be pushing and update to address some of the sync issues soon.  Please try again on 0.0.7

**Comment by JavierRefuerzo** [comment]
Closing issue as resolved in 0.0.7 per email conversation.
