### ISSUE TITLE
Deleted database is overwriting new build

### ISSUE THREAD

**Issue by BitArtOnLine** [UniversalDevicesInc/UD-Mobile-iOS#14]
Tested local network setup: Failed to save credentials to DB due to key/unique error. Attempted several times with different names, etc. - all attempts gave same DB save error.

![IMG_0558](https://user-images.githubusercontent.com/68070280/110672571-c501a500-819d-11eb-957c-161a85df8977.jpeg)

**Comment by BitArtOnLine** [comment]
I deleted v x.6, installed x.7
I don’t know if the DB retains prior records on new install, and there was no indication/display that the local net was already setup. 

The app wouldn’t connect without entering new local net info (which I could never complete). No networks appeared in a list, etc. in the app when I went to set it up.

The auto-searches now work correctly, though.

**Comment by JavierRefuerzo** [comment]
No data should be retained on uninstall...Apple Keychain may hold encrypted usernames and passwords, but it should not interfere with other functions.

Can you clarify if all is working now?

**Comment by BitArtOnLine** [comment]
Just ran through it after portal setup and no error occurred. 
This error happened when app first installed and I tested the local net setup prior to portal testing.

**Comment by JavierRefuerzo** [comment]
My only guess is that it was saved, but did not close the View Controller.  This would then throw an error if it attempted to save again if the View Controller is in the new Network mode instead of edit Network mode.   I tried to reproduce the error on a fresh install twice and can not reproduce.  I'm going to close this, please reopen if encountered again.

**Comment by JavierRefuerzo** [comment]
Reopen issue and rename.  It appears iOS saving database and overwriting existing database with old data.

**Comment by JavierRefuerzo** [comment]
Added URLResouceValue.isExcludedFromBackup for database file e9a59dd2791fdfb1bbe0394d7d1325632664f19a
