### ISSUE TITLE
Typo w/in Setup

### ISSUE THREAD

**Issue by nmayben** [UniversalDevicesInc/UD-Mobile-iOS#15]
Under 'Edit System' > Program and Variable Settings

Requesting the **_satatus_** of all Programs and/or Variables may cause a longer delay when opening the app.
![IMG_8415](https://user-images.githubusercontent.com/80425040/110692221-20d72880-81b4-11eb-9316-7b2217cf0e8d.PNG)

**Comment by JavierRefuerzo** [comment]
Thanks, fixed in 0.0.8 [ce84fa3]
