### ISSUE TITLE
Error changing percent for dimmer on scene

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#19]
![580F0B5A-DAA4-468A-8977-DF0BC5F2B94E](https://user-images.githubusercontent.com/81191799/112235470-b5a64100-8c0c-11eb-85a3-5e7888fd3dcb.png)

**Comment by hart-2-hart** [comment]
This error occur when I selected 100% level.  It changed to 49% and came on.

**Comment by JavierRefuerzo** [comment]
Added .5 second delay between scene percentage commands. Removed scene percentage error notifications. Renamed Status to Estimated Status.
