### ISSUE TITLE
Favorites Order

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#21]
Love this feature.  Able to group significant issues for a room for instance.   

When putting a favorite folder in edit mode, I can drag nodes to desired position but it doesn’t stick.  Hope I’m not seeing something that enables reorder.  

Fantastic!

**Comment by hart-2-hart** [comment]
I know not asking for enhancements yet but planting a bug in your ear..


iBeacon recognition to make a Favorite group be first screen when open app or even better put it on the Apple widget screen would be awesome.

**Comment by JavierRefuerzo** [comment]
Hi Paul,

If the position is not saved this is a bug.  Please send me an email with and attached copy of the backup created by UD Mobile so I can check the database.  This file does not contain user credentials.  

At least one widget with a link to favorites is planned in the near term.  Other items can be add as we have time.

Thanks

**Comment by hart-2-hart** [comment]
Javier,

File sent.  Fully respect UF Mobile being properly built from foundation
up.  Still I could not help but plant that seed.  😉

Paul

**Comment by JavierRefuerzo** [comment]
Fixed sort order for favorites inside folders 5a52a78
