### ISSUE TITLE
Something out of sync turning off and on some scenes

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#22]
In attached image it shows the scene as On by solid circle but it is actually off.  If I go to the device and click On, it will come on.  I go back to screen shown and click icon and it goes Off but status circle stays solid so clicking icon 
![5BBEFB46-4C0F-4409-B651-E953C86D7148](https://user-images.githubusercontent.com/81191799/112737421-75a2cf00-8f28-11eb-82c5-73e08eff609e.jpeg)
again it will not turn on after multiple tries.

**Comment by JavierRefuerzo** [comment]
My best guess is there is a device in the scene which is not reporting a status of "0" (off).   The toggle will attempt to set the scene to off, but this does not guarantee all devices will have a status of "0".   Can you check the scene in the Admin Console and see if there is a child which is not off when off is pressed?

I'll try to add the children in the scene node dashboard, so we can see this from the app. This will also help with issue #23

**Comment by hart-2-hart** [comment]
There is a 8 button mini remote in the scenes and they are of course toggle
send only and show up the last state they sent. I tested a bit and them
being on or off must match UD mobile or the Icon will be in wrong state to
allow it to function.

**Comment by JavierRefuerzo** [comment]
Battery powered devices are listed in the limitations in issue #18 .  The database currently has column to allow users to ignore a child in calculation. However it is not implemented as we have items of higher priority.   We will have to hold off on this until we get some time to implement the ignore flag.

**Comment by hart-2-hart** [comment]
No problem.   Thanks for a incredible product.

It looks great and is not over engineered.  The fact that it works with
nodeserver devices was almost to good to be true.   Pulled up the nodes
fully expecting them to be barebones or not at all.  Bravo!
