### ISSUE TITLE
Missing Status

### ISSUE THREAD

**Issue by gcjacobs** [UniversalDevicesInc/UD-Mobile-iOS#25]
All 2450 IOLinc's v.41 and 2421 TriggerLinc's v.43 are missing their status indicator.  See attached screenshot.

[Screenshot 20210402 at 10341 AM.pdf](https://github.com/UniversalDevicesInc/UD-Mobile-iOS/files/6247816/Screenshot.20210402.at.10341.AM.pdf)

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,
The toggle indicator (filled or empty circle) is currently only available if a device has a property named "Status" and accepts on (DON) and off (DOF) commands.   If this is in favorites it is required that "Status" is the selected property.

Do these devices accept on and off commands?

**Comment by gcjacobs** [comment]
Hi Javi,
No, all of the “sensor” devices report an On or Off as a result of an external event like opening or closing of a door or water level etc.  
You cannot change its state with a (DON) or (DOF) command.

Regards,
Gerry

**Comment by JavierRefuerzo** [comment]
Thanks Gerry,
Closing as Toggle indicator is only available for devices if node accepts (DON) and off (DOF) commands

**Comment by gcjacobs** [comment]
Hi Javi,
If you can’t provide a Toggle indicator for all nodes, I’d recommend eliminating the feature altogether.  
Currently the status is displayed (ON,OFF, %) for all nodes, including sensor nodes.

Regards,
Gerry

**Comment by JavierRefuerzo** [comment]
Hi Gerry,
This would be like saying remove all on and off buttons as all nodes do not have on and off buttons.  The toggle is just a simplified on/off button.

**Comment by gcjacobs** [comment]
Hi Javi,
I disagree, the toggle indicator is redundant and unless it works for all nodes, it will be a source of questioning by users.

Regards,
Gerry

**Comment by JavierRefuerzo** [comment]
Hi Gerry,
We will consider this  in future version based on user feedback.

**Comment by gcjacobs** [comment]
Hi Javi,
That works for me.
Thank you,
Gerry
