### ISSUE TITLE
INSTEON Smoke Sensor status indicator

### ISSUE THREAD

**Issue by gcjacobs** [UniversalDevicesInc/UD-Mobile-iOS#26]
INSTEON Smoke Sensor v.43 does not report status.  See screenshot

[Screenshot 20210402 at 13857 AM.pdf](https://github.com/UniversalDevicesInc/UD-Mobile-iOS/files/6247871/Screenshot.20210402.at.13857.AM.pdf)

**Comment by JavierRefuerzo** [comment]
Hi @gcjacobs ,

I do not own a smoke bridge, so I am unfamiliar with the normal reporting status.  From the screenshot I see some of the nodes do have a status-value and some do not.  Does the Admin Console show status-values for the nodes which do not have a status in UD Mobile?

**Comment by gcjacobs** [comment]
Hi Javi,
The nodes that have a status value are nodes that respond to DON/DOF commands i.e. battery, malfunction, test. 

The others are sensor nodes and respond to an external change, like a change in smoke level or CO levels.

Regards
Gerry

**Comment by JavierRefuerzo** [comment]
Hi Gerry,
So, in regards to the nodes without a status under the node name in UD Mobile; Do these nodes currently have a status in the Admin Console?   

Some devices, including but not limited to battery powered devices, do not have a status in the Admin Console until the device updates the status.  This usually is evident after the ISY is restarted.

**Comment by gcjacobs** [comment]
Hi Javi,
I’m currently upgrading my smoke alarms and the Smoke Bridge is installed in my ISY but not activated. 
None of the nodes respond to DON/DOF commands but some respond to a query. See screenshot
The blank nodes are sensors. 

Handle this issue the same as Issue #25?

Regards,
Gerry
[Screen Shot 2021-04-02 at 2.47.54 PM.png.pdf](https://github.com/UniversalDevicesInc/UD-Mobile-iOS/files/6250957/Screen.Shot.2021-04-02.at.2.47.54.PM.png.pdf)
