### ISSUE TITLE
0.1.2 Security - password limits

### ISSUE THREAD

**Issue by nmayben** [UniversalDevicesInc/UD-Mobile-iOS#27]
Passwords are limited to 20 characters. I had a longer that worked for portal but just had to make a new that was under 20. 

More of an FYI than an issue.

**Comment by JavierRefuerzo** [comment]
@nmayben ,  
Thanks!  I'm done for the day but will look into this soon.

**Comment by JavierRefuerzo** [comment]
Removed secure text entry from custom name field e47626c

**Comment by JavierRefuerzo** [comment]
Hi @nmayben ,
Please let me know where you encountered the password limitation.  I am not able to find this in the app or portal.

**Comment by nmayben** [comment]
> Hi @nmayben ,
> 
> Please let me know where you encountered the password limitation.  I am not able to find this in the app or portal.

I followed the suggested test for this update and added the ISY connection. It kept failing so I verified the password was good using the web interface. I then used reset my password and it did not accept my replacement as it was more than 20 characters. 

Edit:
I just checked my previous password and it was 20 as well, so not exactly why the site was taking it, but the app wasn't.

**Comment by JavierRefuerzo** [comment]
It's possible there is character which is not being accepted.  Do you notice any special characters in the old password which are not in the new password?

**Comment by nmayben** [comment]
The old had a + and ;. The new does not have any.

**Comment by JavierRefuerzo** [comment]
Fixed char encoding for "+" and "&" symbols 0be89aa
