### ISSUE TITLE
Favorite Custom Name triggering password manager

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#28]
With the current release, the Favorite Custom Name  field is triggering my password manager RoboForm  to lookup a password and as I type in the field the letters are replaced by asterisks but it does save the name and work.

**Comment by BitArtOnLine** [comment]
Ditto. When editing a previously set favorite name, asterisks are displayed in the name field. Changing shows PW dialogue.

**Comment by JavierRefuerzo** [comment]
Removed secure text entry from custom name field e47626c
