### ISSUE TITLE
Notification Badge Issue

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#29]
When exiting the program, a notification badge is displayed on the application icon for a moment and then disappears.  I am running UD Mobile in local mode only and have version 0.1.2.  ISY version is 5.3.0.

![UD Mobile-Notification Error](https://user-images.githubusercontent.com/81894103/113498897-ab225c00-94d6-11eb-9145-335d89cc794a.jpg)

**Comment by JavierRefuerzo** [comment]
Hi @mbking1 ,

The icon badge is a carry over from Android.  We have to run services in android for ISY subscriptions and the service requires a notification to prevent it from being killed, this also doubles as a subscription status.   In iOS the notification is only used to show subscriptions status, so when the subscription is closed, or not attempting to connect the icon badge will be removed.  The subscription is, or should be, closed a within a few seconds after dismissing the app. This behavior may change when push notifications are implemented.

If the app has connection issues the notification will pop to show the error, if there is no error the notification is present but does not pop.

**Comment by mbking1** [comment]
Thanks @JavierRefuerzo.  I'm glad to hear that push notifications are going to be added.

This is issue can be closed.  Do you want us to close issues or do you want to do that?

Mark

**Comment by MuxTheFOutOfIt** [comment]
I just started getting the badge on iPhone and iPad.

**Comment by hart-2-hart** [comment]
Just starting getting notification badge on iPad.

**Comment by JavierRefuerzo** [comment]
Thanks @hart-2-hart , this is still on our list

**Comment by JavierRefuerzo** [comment]
UD Mobile connection status has been moved  from notification center to the apps home tab.  App badge now syncs with notification tab.
