### ISSUE TITLE
Folder Name Field Thinks It's a Password for my.isy.io

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#30]
When I try to add a new Folder or edit an existing one, adding a name acts like I'm entering a password.  The characters are hidden and I'm prompted by the iPhone to use my password for my.isy.io.  Ultimately, the folder is created and has the correct name that I entered.  This is new behavior.  It started after I installed 0.1.2 and created an ISY Portal account so I could login to the Universal Devices website to order some products.  Not sure which one is causing this, but seems to make sense that it's the later.  I'm still using a local connection to my ISY in order to avoid issues with MobiLinc Connect.

**Comment by JavierRefuerzo** [comment]
Hi @mbking1 ,
Closing as this is fixed with issue #28 in next release
