### ISSUE TITLE
Favorites Widget 

### ISSUE THREAD

**Issue by hart-2-hart** [UniversalDevicesInc/UD-Mobile-iOS#32]
Favorites widget started showing the Home view instead of Favorites.  Deleted widget, added it back and it’s again showing Favorites again.

**Comment by JavierRefuerzo** [comment]
Verified widget will not open Favorites tab the app is not in memory.

**Comment by JavierRefuerzo** [comment]
Fixed Favorites opening from terminated state 58fa279.   Added App links for scheme to open favorites.  Any url scheme equal to "udmobilewidget" with a path of "widget" will now open favorites i.e "udmobilewidget://link/widget"
