### ISSUE TITLE
Getting iOS app to work with my RCS thermostat

### ISSUE THREAD

**Issue by brianjohanlon** [UniversalDevicesInc/UD-Mobile-iOS#33]
Michael added me to the iOS beta here this afternoon, 4/16.  I got the beta app installed thru TestFlight.  When I launched the app, I was able to give it my ISY portal credentials.  When I look at the screen where the thermostat is listed, none of the fields are populated.  When I moved to another screen (I think I was asked about having the device join the network...  Sorry a little unsure of the dialog), a popup window came up with "Error" as the top window label.  In the middle of the popup window, it says "Connected to Network".  And at the bottom of the popup, it says "1. ERROR Could not get Hub Object from Hub ID.  Notify Developer) and there is a CANCEL link at the bottom of the popup.

If you can help me move forward with using, testing the app and accessing and controlling my thermostat, I'd appreciate it greatly.

Brian O'Hanlon

**Comment by JavierRefuerzo** [comment]
Closing as OP sent email stating Synchronization corrected the issue.
