### ISSUE TITLE
Unable to authenticate on first use

### ISSUE THREAD

**Issue by DaveYYZ** [UniversalDevicesInc/UD-Mobile-iOS#35]
I just downloaded UD Mobile 0.1.14 (14).  I end up with a never-ending loop of iOS modal popups:
ISY Portal
UD Mobile works with....
YES | CANCEL

clicking YES takes me to the Portal login page.  Upon entering credentials (tried using 1Password and regular keyboard) I am returned to the Add System page and the modal popup returns

**Comment by JavierRefuerzo** [comment]
Verified.  A bug was introduced in the last update for onboarding which affects new installs.   I'll try to push a fix ASAP, but it will most likely be 24 - 48 hours until approved by Apple.

In the meantime,  Select "Cancel" when prompted to  setup using ISY Portal.  Add name to the System and save.  Then select "Cancel" when prompted to Synchronize. Now go to the Settings  Tab > ISY Portal Accounts > Add Account (top right), then login.   Click Settings Tab again and go to Systems. Select the System you named in a previous step. Now Select "Add" next to "Portal Account" This should show a list of Portal Accounts. Select  your account and you should be prompted to select an ISY.

**Comment by JavierRefuerzo** [comment]
Subscription Service will no longer restart when adding a new Portal Account.  This caused infinite loop as app would direct user to Systems View Controller if Number of Systems equals zero.  3fcd78c..1f8af55
