### ISSUE TITLE
Label spelled Incorrectly

### ISSUE THREAD

**Issue by BitArtOnLine** [UniversalDevicesInc/UD-Mobile-iOS#36]
Spelling Error
![B366C62F-E2EA-4FFE-83B5-E1233B91774D](https://user-images.githubusercontent.com/68070280/115296351-db9a0500-a128-11eb-9fd7-86fc54d6a553.jpeg)

**Comment by JavierRefuerzo** [comment]
Hi Christopher,
Thanks. Fixed in 695fb57
