### ISSUE TITLE
Garage Door & Status Kit, 74551

### ISSUE THREAD

**Issue by nmayben** [UniversalDevicesInc/UD-Mobile-iOS#38]
My scene appears to be acting funky for my garage doors. What's the best way to set it up to easily use and see the status within UD Mobile?

Thanks

**Comment by JavierRefuerzo** [comment]
Hi @nmayben,
Please provide additional information as this question is very ambiguous.

**Comment by nmayben** [comment]
@JavierRefuerzo Sorry about that, I have a couple garage door setups and the scenes do not seem to work. 

I've attached a screenshot. They need to be pressed multiple times for action. I'm not exactly sure how to read the status as it's in between 1 and 99, versus 0 and 100. 

In MobilincX, it appears as one "device" and you just have to tap to open/close. 

I hope this helps illustrate the issue. 
![image](https://user-images.githubusercontent.com/80425040/118694623-40a15300-b7da-11eb-9e85-deaf254b5f08.png)

**Comment by BitArtOnLine** [comment]
To correct scene On-level, edit the scene and remove Controllers and non-contributing nodes from scene calculation

BitArt Online



Christopher Green

**Comment by JavierRefuerzo** [comment]
Hi @nmayben ,

I'll preference this by acknowledging  don't have a garage so my assumptions about this device may be incorrect, please do let me know if I misunderstand.  

I am assuming your control issue is referring to pressing the toggle (filled or empty blue circle) for operation and not the "on" and "off" buttons.  The toggle for scenes works based on the Estimated Status, so if on (e-status > 0) the "off" command is sent, if off (e-status = 0) then "on" command is sent.  If the on and off buttons (not the toggle) are not working as intended please verify the Admin Console has different operation.  In addition to this changing the Estimated Status percentage may not work for all devices as some devices will not accept a percentage command.

 I think @BitArtOnLine is correct by saying you would need to remove some nodes from the Estimated Status calculation (calculator icon on the right) an only include the door sensor.  This way the app will send the "Off" command if Estimated Status NOT EQUAL TO "0" and will send the "on" command if Estimated Status is EQUAL TO "0".

**Comment by nmayben** [comment]
Thanks @BitArtOnLine and @JavierRefuerzo , I the percentage status is now showing correct. 

The toggling of the scene is not opening the door, I have to open the scene and trigger the relay. To close, however, is working with tapping the scene. I have the same result using the Favorite node as well. 

I'll have to take a look at the Admin Console and see what's up. I tried pressing on and it activated, off did not do anything.

**Comment by nmayben** [comment]
I just switched to Momentary B from A. Seems to be working with the toggle now. 

Now that this is resolved, it's going to muck everything up when I replace the doors soon and possibly change to Liftmaster openers w/ MyQ! LOL

**Comment by JavierRefuerzo** [comment]
Great!
