### ISSUE TITLE
Reading SSID (Wifi network) not working. Verified 0.0.6

### ISSUE THREAD

**Issue by kj4qyf** [UniversalDevicesInc/UD-Mobile-iOS#4]
I am not sure about the purpose of "Add Network" but I seem to be unable to add my local wifi.

**Comment by JavierRefuerzo** [comment]
Verified reading ssid is not working when downloaded from test flight.

**Comment by JavierRefuerzo** [comment]
Added permission to release version to fix issue 0.0.7
