### ISSUE TITLE
Folder Contents Screen Cutoff and Won't Scroll

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#42]
If you select a folder to open when the top level items are partially hidden at the top of the screen, the resulting items in the selected folder are also partially hidden and you can't scroll down to expose the whole item.  See attached screenshots

![IMG_8485](https://user-images.githubusercontent.com/81894103/136623034-35f8abd0-b257-4f9f-88e8-23695c544234.PNG)

![IMG_8486](https://user-images.githubusercontent.com/81894103/136623061-ca345b5f-5300-47b6-8679-6c34a961e230.PNG)

**Comment by JavierRefuerzo** [comment]
Hi @mbking1 ,

Thanks for the report!  Bug has been replicated.
