### ISSUE TITLE
Occasional Error with ISY on Polisy Resets State Variables

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#43]
I occasionally get the following errors with my ISY on Polisy connection which resets all my State Variables.  This error used to be more common and Michel was I think working with you to work out some communications issues.  The errors have become much less frequent, but I still see them from time to time.  Attached are screenshots.

![IMG_8491](https://user-images.githubusercontent.com/81894103/136624094-388a99f6-8f8a-4bee-b144-6469cff7b2d5.PNG)

![IMG_8466](https://user-images.githubusercontent.com/81894103/136624114-bf09e2da-c2fb-4633-8270-212802eb7bdb.PNG)

Mark King

**Comment by JavierRefuerzo** [comment]
Closing issue as it should be resolved with firmware update to Polisy. Follow forum insturctions.
https://forum.universal-devices.com/topic/33924-isy-511-is-now-available/?tab=comments#comment-320195
