### ISSUE TITLE
Home Screen Scrolling Up

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#45]
If I tap a Command button on the Home Screen or return to the Home Screen from viewing a folder's contents, the Home Screen  partially scrolls up.  The top level tiles are cutoff.

![IMG_8803](https://user-images.githubusercontent.com/81894103/145744036-74398199-85a9-474d-9a1c-80b5080d15f9.PNG)

**Comment by JavierRefuerzo** [comment]
Hi @mbking1 ,

Thanks for the report. Fixed scroll position reset on value update in version 0.5.9
