### ISSUE TITLE
Home Screen Scrolls Up When Returning from Folder Contents

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#46]
If you click on a Home Screen folder and then return to the Home Screen, the Home Screen scrolls up.  It's the only scrolling issue I see at the moment.

**Comment by JavierRefuerzo** [comment]
Fixed scroll position restoration on favorites folder back press in version 0.8.9

**Comment by mbking1** [comment]
Thanks!  Works great.

Mark
