### ISSUE TITLE
Clicking  Program Folders in Node Picker Dialog should open Program Folder not Folder's Dashboard

### ISSUE THREAD

**Issue by mbking1** [UniversalDevicesInc/UD-Mobile-iOS#48]
While trying to add a Command to a Command Favorite, I got the following error message when I clicked a Program Folder to open it.  This is the first time I've used Program Folders.  Instead of opening the folder, it thinks I'm selecting the folder as a Command Node.

![IMG_8839](https://user-images.githubusercontent.com/81894103/147000883-44ffb8cc-9d9e-4b8e-9cd5-b57e9ee5dc2d.PNG)

**Comment by JavierRefuerzo** [comment]
Hi @mbking1 ,

Program folders are nodes which only have status values and no controls.  The selection dialog will show all nodes/node-types, so this is the intended message when the app encounters a node with no controls when the user is trying to select a controllable action.  All nodes are shown for consistency among the node picker dialogs. Program Folders may not be the only node without controls.

I'm open to suggestions for changing the text message if you have suggestions.

**Comment by mbking1** [comment]
So it sounds like Program Folders are different from Device Folders.  Clicking on a Device Folder opens it to reveal the devices within it.  I thought the Program Folders would act the same way.  Is it possible to automatically open the folder to reveal the programs within it so the user could then select the one they want to include in the command?  Alternately, I could just not use Program Folders.  I only added one to see how it worked and to organize some common programs.

I think the message is OK as is.  I makes sense.

**Comment by JavierRefuerzo** [comment]
Yes program folders have status values, so they are different, and their status can be used in configure/colors/icons/values.  Clicking on the menu (three dots) of a Program Folder will open the dashboard for the Program Folder. Clicking anywhere else on the Program Folder should open the Folded.  Are the program folders not opening?

**Comment by mbking1** [comment]
No, they don't open.  No matter where I click them, I get the error message and they don't open.  The problem would be solved if they opened.

**Comment by JavierRefuerzo** [comment]
Thanks, that is odd.  Do they open from the Home Tab?

**Comment by mbking1** [comment]
Yes

**Comment by JavierRefuerzo** [comment]
Thanks. I can not replicate. Can you send me a copy of the backup file either via Private  Message on the Forum or to javier at universal-devices dot com ?

**Comment by mbking1** [comment]
So, I got the folder to open if I click in between the folder icon and the menu dots.  Clicking on the icon or the menu dots gives me the error.  I instinctively click on the icon, so it didn't in that scenario.  Not sure why clicking on the menu dots gives the error.  I'll send the backup file to your email.  Thanks for the help.

**Comment by JavierRefuerzo** [comment]
Thanks, replicated.  I agree that clicking a Program Folder icon should open the folder.

**Comment by JavierRefuerzo** [comment]
021beb5 Fixed Program Folder Icon returning Program Folder.  version 0.6.1
