### ISSUE TITLE
Device ON Command Doesn't Work

### ISSUE THREAD

**Issue by BitArtOnLine** [UniversalDevicesInc/UD-Mobile-iOS#5]
(Christopher Green)
Going to a device control page and clicking the ON command does not work.
![IMG_0517](https://user-images.githubusercontent.com/68070280/107087614-b2283900-67c9-11eb-9011-c1013194ad45.jpeg)

1). Device is in Off/0% state; Click "ON" in command (editor) list.
2). UDM performs dome op (progress icon appears briefly).
3). Device status unchanged (verified at the device - it remained in the Off state).
4). Device can be controlled by using right arrow to open On-Level selector; choose 100%; Device activates correctly.

**Comment by JavierRefuerzo** [comment]
Hi Christopher, I think this issue was addressed in our PM

**Comment by BitArtOnLine** [comment]
Don’t think so. Just think the On command is not being sent from the device control panel. However, from the on-level page, all works as expected (same command + on-level).

**Comment by JavierRefuerzo** [comment]
@BitArtOnLine does this issue persist in the latest version?

**Comment by BitArtOnLine** [comment]
It appears to be functioning correctly in 7

Christopher Green

**Comment by JavierRefuerzo** [comment]
Thanks.

Closing as issue appears to be resolved.
