### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by macjeff** [UniversalDevicesInc/UD-Mobile-iOS#53]
If there is a discussion on this please point me in correct direction but I use HOMEBRIDGE with the homebridge-isy-js plugin for only two reasons.  1.  Let me know if doors are unlocked   and   2. Let me know if garage doors are opened or closed     Both of course via Push Notifications.

Yes you can program via PUSH nodeserver, text, or email but they take a while to get through the SMTP and nodeservers so the instant push from homebridge rocks.

Are you adding this?  I am moving to ISY on Polisy and worried the homebridge plugin wont understand ISY on polisy and that will be the end since they dont support it anymore (not for several years!!)

thanks in advance

and UD MOBILE ROCKS!!!   I use Alexa to control everything but sometimes I want to see the exact values of nodeservers and none of the other apps did that but yours does!!!

**Comment by jimboca** [comment]
Just FYI the Push and Notification nodeservers do not use SMTP or email, they use pushover which is very fast. That being said, having push notifications in UDMobile will be great, just not sure it can replace Notification nodeserver for me.

**Comment by JavierRefuerzo** [comment]
Hi Jeff,

UD Mobile client side will accept push, but we still need server side.  So in time it will be possible, but has a lower priority compared to a few other items. With that said even after server side implementation, the setup will likely be in the form of a Node Server similar to the Notification Node Server. If permitting we may be able to include setup in the current Notification Node Server.

I also use the Notification Node Server with PushOver.  It has been solid for over a year with no missed notifications. Most arriving within 1-5 seconds, and you can use Network Resources to customize the notification. If I remember correctly the Notification NS will also queue messages in case there is an internet outage.

**Comment by JavierRefuerzo** [comment]
Push Added in version 0.7.8

**Comment by macjeff** [comment]
Can you tell me how it works?

Jeff

On Jun 20, 2022, at 3:49 PM, Javi ***@***.******@***.***>> wrote:



Push Added in version 0.7.8

**Comment by JavierRefuerzo** [comment]
Hi Jeff,
Here are instructions using Network Resources. 
https://wiki.universal-devices.com/index.php?title=UD_Mobile#Notifications_Tab

 We are planning to build a Node Server or have a NS built at some point in the future. See this comment for more info:
https://forum.universal-devices.com/topic/37001-notifications-release-for-ios/?do=findComment&comment=341747

**Comment by macjeff** [comment]
I can do it but will wait.  Hopefully when done it will be a nodeserver you can add strings and then send those strings via push.

Jeff

On Jun 20, 2022, at 4:11 PM, Javi ***@***.******@***.***>> wrote:



Hi Jeff,
Here are instructions using Network Resources.
https://wiki.universal-devices.com/index.php?title=UD_Mobile#Notifications_Tab

We are planning to build a Node Server or have a NS built at some point in the future. See this comment for more info:
https://forum.universal-devices.com/topic/37001-notifications-release-for-ios/?do=findComment&comment=341747

**Comment by macjeff** [comment]
I was told by Jimbo that his notification nodeserver support your announcements.  Do you have info on how to do that?  Or should I still wait for your nodeserver?

**Comment by JavierRefuerzo** [comment]
Hi Jeff,  UD is/was in talks with Jimbo regarding using his Node Server but that is beyond my role.   At this time I have not started anything.  

I also user Jimbo's node server and it has worked well for pushover for the last couple of years.  I believe UD Mobile integration is still in beta, but others have tested and used it successfully.  See: https://forum.universal-devices.com/topic/37058-ud-mobile-notifications-support/?do=findComment&comment=342475
