### ISSUE TITLE
Move the Delete ISY Button Away From The Save Button

### ISSUE THREAD

**Issue by BitArtOnLine** [UniversalDevicesInc/UD-Mobile-iOS#7]
In testing I have accidentally touched/clicked the Delete [ISY] button, several times.
Also, please increase the size of the icons in the buttons. On my 11P, with a larger screen, buttons are tiny. I believe the font size equivalent is 15/16 pt for icons.

**Comment by JavierRefuerzo** [comment]
Please post and image.  The save and delete buttons sizes are set by the system on the top Nav Bar, but will look into this.

**Comment by JavierRefuerzo** [comment]
Added 20px space between save and delete buttons in systems view controller in 0.0.7
