### ISSUE TITLE
SQLite Authorization Denied on some devices in background.

### ISSUE THREAD

**Issue by JavierRefuerzo** [UniversalDevicesInc/UD-Mobile-iOS#96]
The issues is caused by iOS refusing to let the app read it's own files when the app is in the background.  Firebase reports 3 users with this crash in the last 30 days, but each user has many crashes. The devices are 13, 13-mini, and 14 pro on 17.4.1 & 17.3.1.

`
Crashed: com.apple.main-thread
0  libswiftCore.dylib             0x398c0 _assertionFailure(_:_:file:line:flags:) + 264

1  Go2iSY                         0x38fe18 specialized SceneDelegate.scene(_:willConnectTo:options:) + 35 (SceneDelegate.swift:35)

2  Go2iSY                         0x38ac04 @objc SceneDelegate.scene(_:willConnectTo:options:) + 4302056452 (<compiler-generated>:4302056452)
3  UIKitCore                      0x1923b4 +[UIScene _sceneForFBSScene:create:withSession:connectionOptions:] + 1080
4  UIKitCore                      0x24e3b8 -[UIApplication _connectUISceneFromFBSScene:transitionContext:] + 808
5  UIKitCore                      0x24dee0 -[UIApplication workspace:didCreateScene:withTransitionContext:completion:] + 360
....
25 ???                            0x1b2472d84 (Missing)
`

`crash_info_entry_0	 Go2iSY/SceneDelegate.swift:35: Fatal error: SQLite error 23: authorization denied`

Possibly related to:
https://github.com/tekartik/sqflite/pull/935
https://github.com/groue/GRDB.swift/issues/571

**Comment by JavierRefuerzo** [comment]
Fixed in 1.1.73
Backup import will now reset imported files to FileProtectionType.completeUntilFirstUserAuthentication
Existing files with incorrect FileProtectionType will present an error to users and allow reset in Backup View.

**Comment by JavierRefuerzo** [comment]
Changing the File protection type did not correct the issue.

**Comment by JavierRefuerzo** [comment]
Added 5 loops with 5 second delay. Based on logs it  appears the database will initialize a short time later.  So maybe this delay will allow time for the database to start.

**Comment by Mattijah** [comment]
Experiencing same issue here, but I don't even run the app in the background. It seems to only occur to small number of users. Very odd

**Comment by JavierRefuerzo** [comment]
@Mattijah do you use Geofencing?

**Comment by Mattijah** [comment]
I don't. The crash occurs at the start when trying to open respectively create database file.

**Comment by JavierRefuerzo** [comment]
Ok Thanks.  I did not know this was being shown to users. All previous reporters had geofencing issues with no crashes except in lower level logs with time/device correlations to crashes reported by Firebase.

Can you please share as screenshot of he crash message?   What is the frequency?  When did this start (i.e. iOS version upgrade?)?

**Comment by Mattijah** [comment]
Started happening on iOS 16/17. I am unable to reproduce it no matter what I do though... Error logs are pretty useless to be completely honest. The only useful information I got is that it returns error 23 "authorization denied". I don't have information as to exactly how many users are experiencing this at the moment, but it is small number. Probably like 5% if not less. As to frequency, once it starts happening it seems it just keeps going on... I have 43 reports from a single user for example.

**Comment by JavierRefuerzo** [comment]
@Mattijah is this on UD Mobile iOS app or another application?

**Comment by JavierRefuerzo** [comment]
@Mattijah if not UD Mobile, app may be in the background for app warming/prewarming so databases must be started from Scene Delegate not AppDelegate.   The loop with delay seems to have solved most but not all crashes in our app.
